### ISSUE TITLE
[feature request] tmux-session

### ISSUE THREAD

**Issue by lmartak** [mislav/dotfiles#13]
Hi, 

if you'd be able to elaborate `# TODO: persist and restore the state & position of panes.` in [https://github.com/mislav/dotfiles/blob/master/bin/tmux-session](tmux-session) anytime soon, I would much appreciate it :)

Thanks for any response!

**Comment by gcorrel** [comment]
So, what are the steps required to use this script? Just saving it to home directory or what? Do you mind outlining the steps one must take to have it working properly please? 

Thank you in advance.

**Comment by lmartak** [comment]
Update: I've replaced [tmux-session](https://github.com/mislav/dotfiles/blob/master/bin/tmux-session) with tmux plugins managed via [tpm](https://github.com/tmux-plugins/tpm/), namely:

- [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect)
- [tmux-continuum](https://github.com/tmux-plugins/tmux-continuum)
- [tmux-sensible](https://github.com/tmux-plugins/tmux-sensible)

and I'm perfectly satisfied with the features I get with this setup so this is no longer an issue for me. I am thus closing the issue and recommending anyone reading this the plugins linked above.

**Comment by mislav** [comment]
@lmartak Thank you for those resources! ✨
